### ISSUE TITLE
Add to Gradle Source Dependencies

### ISSUE THREAD

**Issue by martin-braun** [Gkemon/Lovely-Android-Loading#2]
I found your answer [here](https://stackoverflow.com/a/63894792/1540350) and I want to try it, however I would like to pull it using Gradle Source Dependencies like all the other libraries. 

Could you make it available?

**Comment by Gkemon** [comment]
Hi @martin-braun  , I have just added Gradle source dependencies. Please check and feel free to knock me if you find any complexity. Thank you.

**Comment by martin-braun** [comment]
Thank you! 🙏🏻 Can't wait to use it on my next Android project.
