### ISSUE TITLE
Not Working ...

### ISSUE THREAD

**Issue by Kayuemkhan** [Gkemon/Lovely-Android-Loading#5]
I added all of the dependencies and also checked in java and kotlin project! 
but, no loading is showing..

**Comment by Kunnu123** [comment]
Hello @Kayuemkhan update dependency

 implementation 'com.github.Gkemon:Easy-Android-Loading:1.2'

**Comment by Gkemon** [comment]
Hi @Kunnu123 @Kayuemkhan  
Thank you all for the support. Please kindly star and fork and send me the app links you all are using it. If there is no confidentiality then I will list them in my readme.md file.
